name: CI (CPU)

on:
  push:
    branches:
      - main
      - "member-function-customization"
      - "pull-request/[0-9]+"
      - "test-ci*"

concurrency:
  group: ${{ github.workflow }}-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  build-cpu-windows:
    runs-on: windows-2022
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: "cl",       build: "Debug",   name: "CPU (Windows) (msvc, Debug)" }
          - { compiler: "cl",       build: "Release", name: "CPU (Windows) (msvc, Release)" }
          #- { compiler: "clang++",  build: "Debug",   name: "CPU (Windows) (clang, Debug)" }
          #- { compiler: "clang++",  build: "Release", name: "CPU (Windows) (clang, Release)" }
          #- { compiler: "clang-cl", build: "Debug",   name: "CPU (Windows) (clang-cl, Debug)" }
          #- { compiler: "clang-cl", build: "Release", name: "CPU (Windows) (clang-cl, Release)" }

    steps:
      - name: Checkout stdexec (Windows)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build and test CPU schedulers (Windows)
        shell: pwsh
        run: |
          docker pull rapidsai/devcontainers:24.12-cuda12.6-cl14.39-windows2022
          docker run --isolation=process -v "$(pwd):C:/stdexec" rapidsai/devcontainers:24.12-cuda12.6-cl14.39-windows2022 powershell C:/stdexec/.github/workflows/test-windows.ps1 -Compiler '${{ matrix.compiler }}' -Config '${{ matrix.build }}'

  ci-cpu-windows:
    runs-on: windows-latest
    name: CI (CPU) (Windows)
    needs:
      - build-cpu-windows
    steps:
      - run: echo "CI (CPU) (Windows) success"
